name: ourESchool
description: A School Management Project
publish_to: "none"
version: 1.0.0-dev.1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: 0.7.0
  cloud_firestore: 0.16.0
  cupertino_icons: ^1.0.0
  custom_radio_grouped_button: 1.0.0
  dio: ^3.0.10
  division: ^0.8.8
  file_picker: ^2.1.4
  firebase_auth: 0.20.0+1
  firebase_core: 0.7.0
  firebase_storage: 7.0.0
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.7.0
  get_it: ^5.0.3
  http: ^0.12.2
  image: ^2.1.4
  image_picker: ^0.6.7+17
  image_picker_for_web: ^0.1.0+2
  intl: ^0.16.1
  intro_views_flutter: ^2.8.2
  path_provider: ^1.6.1
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.3
  provider: ^4.3.2+3
  random_color: ^1.0.5
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   rxdart: ^0.22.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Italic.ttf
